# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecPay', '0002_auto_20160627_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payDate', models.DateField(verbose_name='\u65e5\u671f')),
                ('paySerialNo', models.CharField(blank=True, default='', max_length=20, verbose_name='\u652f\u51fa\u51ed\u8bc1\u53f7')),
                ('payClient', models.CharField(blank=True, max_length=30, verbose_name='\u5546\u6237')),
                ('payMerchant', models.CharField(max_length=12, verbose_name='\u5546\u54c1')),
                ('payPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='\u5355\u4ef7')),
                ('payTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='\u603b\u4ef7')),
                ('payMaker', models.CharField(default='', max_length=12, verbose_name='\u7ecf\u624b\u4eba')),
                ('payChecker', models.CharField(blank=True, max_length=12, verbose_name='\u5ba1\u6838\u4eba')),
                ('payMemo', models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name': '\u652f\u51fa',
                'verbose_name_plural': '\u652f\u51fa',
            },
        ),
    ]
